### ISSUE TITLE
[Help]Configure Alchemical for testing

### ISSUE THREAD

**Issue by lewoudar** [miguelgrinberg/alchemical#13]
Hi Miguel,
sorry to write this kind of issue here, but since there are no `discussions` set, here I go. My issue is to find a correct way to set Alchemical object in both code and tests. Do you know resources/examples to configure properly Alchemical?

For my use case I set up configuration using [Pydantic v1](https://docs.pydantic.dev/1.10/usage/settings/) model via environment variables. This is where I set the connection string.

config.py module
```python
from pydantic import BaseSettings, PostgresDsn


class Configuration(BaseSettings):
    db_connection_string: PostgresDsn | str = 'sqlite+pysqlite:///:memory:'

    class Config:
        env_prefix = 'ar_'
```

And I have a models.py module where I declare the Alchemical object and database models

```python
from .config import Configuration

db = Configuration().db_connection_string


class Job(db.Model):
    __tablename__ = 'jobs'

    id: Mapped[uuid.UUID] = mapped_column(Uuid, primary_key=True, default=uuid.uuid4)
    name: Mapped[str] = mapped_column(String(50))
   ...
```

And now in my conftest.py module (I'm using Pytest for tests), I tried to set an environment variable to configure the connection string differently

```python
@pytest.fixture(autouse=True)
def db_session(monkeypatch, mocker) -> Session:
    """Creates and deletes a test database."""
    monkeypatch.setenv('ar_db_connection_string', 'sqlite+pysqlite:///:memory:')
 
    # ugly but necessary
    from project.models import db

    db.create_all()
    with db.Session() as session:
        yield session
    db.drop_all()
```

This does not work because the configuration object is set before entering the fixture (I saw it with some breakpoints). I have no clue how to organize it differently. If you have the slightest suggestion, I'm interested.

**Comment by miguelgrinberg** [comment]
You can create the Alchemical instance without any arguments, then call `initialize()` with your configuration later, after you have a configuration object ready.

```python
db = Alchemical()

def init_db():
    db.initialize(url="...")

class User(db.Model):
    # ...
```

With this solution you are delaying the initialization, so this gives you time to prepare your configuration.

**Comment by lewoudar** [comment]
Thanks Miguel, I use the `initialize` method to change the URL in my fixture and it works pretty well now.
