### ISSUE TITLE
Listening for database events in Alchemical

### ISSUE THREAD

**Issue by gcalabria** [miguelgrinberg/alchemical#16]
Before going to my question, first I would like to thank you for your work, it is really amazing! I've watched/ read most of your tutorials and learned so much! It is incredible how you make complex topics feel so easy.

Now, let's start with the question. I am trying to implement a search functionality using Flask, react, apifairy, and Alchemical. In your mega flask tutorial, you add listeners (_after_commit_ and _before_commit_) to the database in order to keep the elasticsearch indices and the db instance in sync. However, in the mega flask tutorial, you use SQLAlchemy, and I am using Alchemical. Is it possible to listen for events with alchemical?

Any help is appreciated :)

**Comment by miguelgrinberg** [comment]
Alchemical does not need to be involved with event handlers, you can use SQLAlchemy's event subsystem directly.

**Comment by gcalabria** [comment]
Wow! That was a fast answer :)

I am not really sure how to do that 😆.

As I understand, the `db` variable in the app is an instance of Alchemical ([example](https://github.com/miguelgrinberg/microblog-api/blob/ed1cd1c5dedbea6264a8857db68e4e79d3bccbad/api/app.py#L9)), and the listeners are attached using it ([example](https://github.com/miguelgrinberg/microblog/blob/3472187155ba60d36aa819cf4e6dbfeefeadf2fa/app/models.py#L56C2-L56C2)).

So what I added this to my `models.py` file:
```python
from sqlalchemy.event import listen

listen(db.session, "after_commit", SearchableMixin.after_commit)
```

However, when I try to access `db.session` from my `models.py` file, I get an error `Working outside of application context.`.

Is my approach correct? If yes, where would be a good place to attach the listeners?

Thanks a lot 😀

**Comment by miguelgrinberg** [comment]
The code you are using as a base uses Flask-SQLAlchemy, not Alchemical.

To set up a session event you have to pass the session class, which is `db.Session` (uppercase "S").

    listen(db.Session, "after_commit", SearchableMixin.after_commit)

**Comment by gcalabria** [comment]
That worked perfectly. Thank you very much 😀
