### ISSUE TITLE
alchemical.aio.Alchemical with Flask and Flask-Migrate

### ISSUE THREAD

**Issue by wgwz** [miguelgrinberg/alchemical#2]
Hey Miguel :wave: I hope all is well! I'm wondering if I could use Flask, and the as alchemical.aio.Alchemical object with Flask-Migrate. This seems like a combination that is probably not possible but I hope I'm wrong. For a somewhat artificial reason, I'm happy with uwsgi as my application server, and I don't want to switch over to aioflask/asgi/etc just yet. I've discovered some features in uwsgi that are keeping me there (for now). I'm interested in being able to get migrations, and utilize the new async support in Flask. Alchemical seems to get me really close! Curious to hear your thoughts on this, any advice appreciated.

**Comment by miguelgrinberg** [comment]
The async support in Flask is not very useful, so I don't intend to support it in Alchemical. I'm not sure if the `aio.Alchemical` class will work with it or not, but it might. You will not be able to use the Flask integration, though, it would be just creating the `aio.Alchemical` object and using it more or less like you would in a FastAPI application.

**Comment by wgwz** [comment]
I see. I think I may be better off with a different approach in this scenario, not to any fault of this project. I think may not be the right fit for my set of constraints. There’s probably a path of a less resistance with another approach. But I’ve not entirely given up yet. Maybe there is something I can work by just using Alembic directly rather than Flask-Migrate (which pains me a little because I like it…) while still using Alchemical
