### ISSUE TITLE
Multiple Database documentation. 

### ISSUE THREAD

**Issue by Fr4nks** [miguelgrinberg/alchemical#3]
I like the new way (in example files) of doing multiple databases more than the documentation on https://alchemical.readthedocs.io/en/latest/usage.html
Its a lot closer to the SQLAlchemy standard. 
config.py
```python
    ALCHEMICAL_DATABASE_URL = os.environ.get('DATABASE_URL') or \
        'sqlite:///' + os.path.join(basedir, 'db.sqlite')
    ALCHEMICAL_BINDS = {'firebird': 'firebird+fdb://sysdba:masterkey@localhost:3050/' + basedir + '\\DATA.FDB'}
```
Thankyou, no real issue, just posting here for anybody else who is currently working with multiple databases.

**Comment by miguelgrinberg** [comment]
I'm guessing the examples you are looking at use the Flask, which has a configuration object. The documentation that you are reading is generic, not specific about using this package with Flask, so there is no configuration object in which these options can be added. The section about using Flask lists the configuration variables, by the way, I don't believe there is anything missing in the documentation.

**Comment by Fr4nks** [comment]
Yes, 100%. I am a bit clouded into thinking everybody uses flask.
