### ISSUE TITLE
How do I track session changes with events?

### ISSUE THREAD

**Issue by collinsmarra** [miguelgrinberg/alchemical#5]

**Comment by collinsmarra** [comment]
How do I track session changes with events?

I am trying to use elastic search for my app. So I was reading the micro-blog  tutorial and it use flask-sqlalchemy. So events are implemented this way:

![image](https://user-images.githubusercontent.com/48761741/156142728-b76786ea-b5f9-477e-bfc6-64e840ef6585.png)

I was trying to do the same with `alchemical` but I cannot use `sqlalchemy.events` because that would result in `RuntimeError: Working outside of application context.`

**Comment by miguelgrinberg** [comment]
I'm not sure what is the usage that gives you working outside of app context, but Alchemical does not try to override SQLAlchemy as much as Flask-SQLAlchemy does. Setting events is done directly through SQLAlchemy, as documented here: https://docs.sqlalchemy.org/en/14/core/event.html#event-registration.

**Comment by collinsmarra** [comment]
![image](https://user-images.githubusercontent.com/48761741/156165045-45273df2-ac0b-4f10-88fa-108bd481013a.png)

I think that would be the line that causes the error

**Comment by collinsmarra** [comment]
Thanks. `db.Session` (uppercase) would result in an error **No such event 'before_commit' for target**.
However `db.session_class` works. I am yet to investigate and learn. Thanks again

**Comment by miguelgrinberg** [comment]
Ah, right! `db.Session` is a method that returns an instance of `db.session_class`, so yeah, what you did is what I intended to suggest.
