### ISSUE TITLE
Inheritance mapping: [single-table, joined-table, and concrete-table] does not seem to work.

### ISSUE THREAD

**Issue by born2discover** [miguelgrinberg/alchemical#7]
Greetings,

Attempting to port an application to Alchemical, I seem to have stumbled upon a peculiar case. The application in question uses Single-Table Inheritance for some models and Alchemical does not seem to be able to load them and breaks with the following error:

`sqlalchemy.exc.InvalidRequestError: Row with identity key (<class '__main__.Base'>, (1,), None) can't be loaded into an object; the polymorphic discriminator column 'children.type' refers to mapped class B->children, which is not a sub-mapper of the requested mapped class A->children`

At first I thought the bug resided in the application, but after some investigations, it really seems to be boiling down to Alchemical. Consider the following example:

Using:
- Alchemical: 0.5.1
- SQLAlchemy: 1.4.24
- Python: 3.10.5

Minimal example with vanilla SQLAlchemy:

```python
import os
from sqlalchemy import Column, Integer, String, ForeignKey, create_engine
from sqlalchemy.ext.declarative import declared_attr
from sqlalchemy.orm import relationship, Session, declarative_base

Model = declarative_base()

class Parent(Model):
    __tablename__ = "parents"

    id = Column(Integer, primary_key=True)
    title = Column(String, nullable=True)

    all_a = relationship("A", backref="parent", foreign_keys="A.parent_id", cascade="all, delete-orphan")
    all_b = relationship("B", backref="parent", foreign_keys="B.parent_id", cascade="all, delete-orphan")


class Base(Model):
    __tablename__ = "children"

    id = Column(Integer, primary_key=True)
    title = Column(String, nullable=True)
    type = Column(String, nullable=False)

    @declared_attr
    def parent_id(self):
        return Column(Integer, ForeignKey("parents.id"), nullable=False)

    __mapper_args__ = {"polymorphic_on": type, "polymorphic_identity": "BASE"}


class A(Base):
    __mapper_args__ = {"polymorphic_identity": "A"}


class B(Base):
    __mapper_args__ = {"polymorphic_identity": "B"}


engine = create_engine(f"sqlite:///{os.path.join(os.getcwd(), 'database.db')}", echo=False, future=True)
Model.metadata.create_all(engine)
session = Session(engine)

p = Parent(title="Parent 1")
p.all_a.append(A(title="Child A1"))
p.all_b.append(B(title="Child B1"))

session.add(p)
session.commit()
session.close()

session = Session(engine)
p = session.get(Parent, 1)
print("-> ", p.title)
print("a: ", p.all_a)
print("b: ", p.all_b)
```

The result should look somewhat similar to this:

```bash
->  Parent 1
a:  [<__main__.A object at 0x7***>]
b:  [<__main__.B object at 0x7***>]
```

The same code adapted to using Alchemical:

```python
import os
from sqlalchemy import Column, Integer, String, ForeignKey
from sqlalchemy.ext.declarative import declared_attr
from sqlalchemy.orm import relationship

db = Alchemical(url=f"sqlite:///{os.path.join(os.getcwd(), 'database.db')}")

class Parent(db.Model):
    __tablename__ = "parents"

    id = Column(Integer, primary_key=True)
    title = Column(String, nullable=True)

    all_a = relationship("A", backref="parent", foreign_keys="A.parent_id", cascade="all, delete-orphan")
    all_b = relationship("B", backref="parent", foreign_keys="B.parent_id", cascade="all, delete-orphan")


class Base(db.Model):
    __tablename__ = "children"

    id = Column(Integer, primary_key=True)
    title = Column(String, nullable=True)
    type = Column(String, nullable=False)

    @declared_attr
    def parent_id(self):
        return Column(Integer, ForeignKey("parents.id"), nullable=False)

    __mapper_args__ = {"polymorphic_on": type, "polymorphic_identity": "BASE"}


class A(Base):
    __mapper_args__ = {"polymorphic_identity": "A"}


class B(Base):
    __mapper_args__ = {"polymorphic_identity": "B"}

db.create_all()

with db.Session() as session:
    p = Parent(title="Parent 1")
    p.all_a.append(A(title="Child A1"))
    p.all_b.append(B(title="Child B1"))

    session.add(p)
    session.commit()
    session.close()

with db.Session() as session:
    p = session.get(Parent, 1)
    print("-> ", p.title)
    print("a: ", p.all_a)
    print("b: ", p.all_b)
```

Alchemical code produces the following result:

```bash
->  Parent 1
Traceback (most recent call last):

[... amended for brevity ...]

sqlalchemy.exc.InvalidRequestError: Row with identity key (<class '__main__.Base'>, (2,), None) can't be loaded into an object; the polymorphic discriminator column 'children.type' refers to mapped class B->children, which is not a sub-mapper of the requested mapped class A->children
```
Am I missing something? I went through the documentation several times but did not find anything relating to table inheritance or polymorphic relationships, so I presume it works identically to the vanilla SQLAlchemy.

The example above is an adapted version of the [single-table inheritance](https://docs.sqlalchemy.org/en/14/_modules/examples/inheritance/single.html) as demonstrated in the SQLAlchemy docs.

**Comment by miguelgrinberg** [comment]
Interesting issue!

This appears to be an issue or limitation in SQLAlchemy, actually, not Alchemical. Alchemical adds a default `__tablename__` attribute to the declarative base model class, so that model classes in your application get a default table name. In plain SQLAlchemy you have to manually add `__tablename__` to your models.

I'm not sure why, but this difference is what breaks the polymorphic usage. To make it work with Alchemical, you can add `__tablename__ = None` to your `A` and `B` model classes. If you want to see how your plain SQLAlchemy example breaks, add `Model.__tablename__ = 'foo'` right after you create your declarative base.

**Comment by born2discover** [comment]
Thank you @miguelgrinberg!

Silly me, I didn't even consider table names as possible culprits. That was indeed the issue.
Overriding table names with `None` does indeed solve it.

```python
class A(Base):
    __tablename__ = None
    __mapper_args__ = {"polymorphic_identity": "A"}


class B(Base):
    __tablename__ = None
    __mapper_args__ = {"polymorphic_identity": "B"}
```

Thank you!
