### ISSUE TITLE
Check if the table exists

### ISSUE THREAD

**Issue by vinrap** [miguelgrinberg/alchemical#8]
In Alchemical library is there a way to know if the table in database already exists?
if yes how?

Why do i need this functionality: i was trying to initiate the tables with "flask db upgrade" that didnt not create the tables. so had to use "db.create_all()" in code. 
i dont want db.create_all() to be created again after running it, so better to check if table does not exists then create it. 

i checked in sqlalchemy this functionality exists ([link](https://docs.sqlalchemy.org/en/14/core/reflection.html#sqlalchemy.engine.reflection.Inspector.has_table))

**Comment by miguelgrinberg** [comment]
Alchemical is a thin wrapper around SQLAlchemy. Anything you want to do with SQLAlchemy you can do with Alchemical, just get a session (which is a standard SQLAlchemy session) and do what you need to do.
