### ISSUE TITLE
run an arbitrary SQL statement on the database not accurate

### ISSUE THREAD

**Issue by dhernandezgt** [miguelgrinberg/alchemical#9]
Hola Miguel, 

Documentation indicated use db.text() however attribute does not exist.

![image](https://user-images.githubusercontent.com/39681206/217154746-5a5df0ee-7110-41bd-86af-78d21dabda56.png)

Here is python modules in my enviroment.

![image](https://user-images.githubusercontent.com/39681206/217155071-406be24f-0539-40ec-a66d-8c48b06b219e.png)

**Comment by miguelgrinberg** [comment]
Sorry about that. The correct way to do this is to import`text` from sqlalchemy:

    from sqlalchemy import text
